### ISSUE TITLE
sap-btp-operator-controller-manager goes OOM CrashLoopBackOff 3000+ times

### ISSUE THREAD

**Issue by chuasweechin** [SAP/sap-btp-service-operator#279]
Hi Team,

We install sap-btp-operator in many environments and we found OOM CrashLoopBackOff error in some of the environments.
It seems to happen for specific environment only. We have tried to increase the memory for the pod but it does not help.
<img width="831" alt="Screenshot 2023-04-22 at 10 24 50 AM" src="https://user-images.githubusercontent.com/22762719/233757071-a83e879a-fcbd-4304-afd7-5fe2424a5469.png">

It seems to be very similar to an earlier issue that has been previously reported: https://github.com/SAP/sap-btp-service-operator/issues/233. Based on the issue, we have also check and confirm that nothing is wrong with cert-manager in our cluster. It seems that the pod always crashes upon startup. I also confirmed that there is 0 ServiceInstance and 0 ServiceBinding CR created in our cluster.

**Details:**
We are running the pod with `ghcr.io/sap/sap-btp-service-operator/controller:v0.2.0`.
I have check and confirm that the allocated node has enough memory and cpu resource for the pod to run.

This is my Pod resource spec section:
```
resources:
    limits:
        cpu: 500m
        memory: 1000Mi
    requests:
        cpu: 100m
        memory: 200Mi
```

This is the error log I got from the Pod:
```
i567221@TLD6YYWVHT ~ % k logs sap-btp-operator-controller-manager-6566bc55d4-dr8sd  -c manager
I0421 03:19:28.830751       1 request.go:655] Throttling request took 1.036414745s, request: GET:https://api.prod-us.mlfprod.internal.live.k8s.ondemand.com:443/apis/serving.knative.dev/v1?timeout=32s
2023-04-21T03:19:30.086Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2023-04-21T03:19:30.087Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/mutate-services-cloud-sap-com-v1-serviceinstance"}
2023-04-21T03:19:30.087Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/mutate-services-cloud-sap-com-v1-servicebinding"}
2023-04-21T03:19:30.087Z	INFO	controller-runtime.builder	skip registering a mutating webhook, admission.Defaulter interface is not implemented	{"GVK": "services.cloud.sap.com/v1, Kind=ServiceBinding"}
2023-04-21T03:19:30.087Z	INFO	controller-runtime.builder	Registering a validating webhook	{"GVK": "services.cloud.sap.com/v1, Kind=ServiceBinding", "path": "/validate-services-cloud-sap-com-v1-servicebinding"}
2023-04-21T03:19:30.087Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/validate-services-cloud-sap-com-v1-servicebinding"}
2023-04-21T03:19:30.087Z	INFO	setup	starting manager
I0421 03:19:30.087513       1 leaderelection.go:243] attempting to acquire leader lease sap-btp-operator/aa689ecc.cloud.sap.com...
2023-04-21T03:19:30.087Z	INFO	controller-runtime.webhook.webhooks	starting webhook server
2023-04-21T03:19:30.087Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2023-04-21T03:19:30.087Z	INFO	controller-runtime.certwatcher	Updated current TLS certificate
2023-04-21T03:19:30.087Z	INFO	controller-runtime.webhook	serving webhook server	{"host": "", "port": 9443}
2023-04-21T03:19:30.087Z	INFO	controller-runtime.certwatcher	Starting certificate watcher
I0421 03:19:45.602998       1 leaderelection.go:253] successfully acquired lease sap-btp-operator/aa689ecc.cloud.sap.com
2023-04-21T03:19:45.603Z	INFO	controller-runtime.manager.controller.servicebinding	Starting EventSource	{"reconciler group": "services.cloud.sap.com", "reconciler kind": "ServiceBinding", "source": "kind source: /, Kind="}
2023-04-21T03:19:45.603Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"sap-btp-operator","name":"aa689ecc.cloud.sap.com","uid":"7eb582c1-858b-4918-a59c-108287818bc4","apiVersion":"v1","resourceVersion":"3699749860"}, "reason": "LeaderElection", "message": "sap-btp-operator-controller-manager-6566bc55d4-dr8sd_3401213d-d4af-4021-8a65-5647c0eedeee became leader"}
2023-04-21T03:19:45.603Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Lease","namespace":"sap-btp-operator","name":"aa689ecc.cloud.sap.com","uid":"34fdceff-9ab9-4691-b3e0-edfed6f89d9c","apiVersion":"coordination.k8s.io/v1","resourceVersion":"3699749861"}, "reason": "LeaderElection", "message": "sap-btp-operator-controller-manager-6566bc55d4-dr8sd_3401213d-d4af-4021-8a65-5647c0eedeee became leader"}
2023-04-21T03:19:45.603Z	INFO	controller-runtime.manager.controller.serviceinstance	Starting EventSource	{"reconciler group": "services.cloud.sap.com", "reconciler kind": "ServiceInstance", "source": "kind source: /, Kind="}
2023-04-21T03:19:45.703Z	INFO	controller-runtime.manager.controller.servicebinding	Starting EventSource	{"reconciler group": "services.cloud.sap.com", "reconciler kind": "ServiceBinding", "source": "kind source: /, Kind="}
2023-04-21T03:19:45.704Z	INFO	controller-runtime.manager.controller.serviceinstance	Starting Controller	{"reconciler group": "services.cloud.sap.com", "reconciler kind": "ServiceInstance"}
```

**Comment by kerenlahav** [comment]
Hi,
First, you are using a very old release (released more than a year ago), have you tried to use the latest?
You are using the same release on other environments and you don't encounter the issue so it seems like something in your cluster configuration and not related to the btp operator, have you compared the clusters? same cert manager is used in both?

**Comment by chuasweechin** [comment]
Hi Keren,

We will try upgrading to the latest v0.4.2 and try it again. 

In theory, our clusters should all be in sync as they are all managed via automation. But I will need to confirm this to be sure nothing is misconfigured. 

To check, why would cert manager cause OOM issue in starting up of btp-operator? Is there some kind of hard dependencies between these components?

**Comment by kerenlahav** [comment]
The certificate is required for webhooks execution, it shouldn't cause OOM to the BTP operator pod, I'm unaware of what was fixed in issue [#233 ](https://github.com/SAP/sap-btp-service-operator/issues/233) since he resolved it by himself.

**Comment by chuasweechin** [comment]
Sounds good. I will continue the investigation at my end. 
Will provide an update if I got new findings after my upgrade to v0.4.2.

**Comment by piotrmiskiewicz** [comment]
Hi @kerenlahav, I suspect that the http client is created as a new object every time it is needed. http.Client must be shared because it is thread safe. Can you check this?

**Comment by kerenlahav** [comment]
Hi Pioter,
The client is created every time because it might be different per resource.
Thanks

**Comment by piotrmiskiewicz** [comment]
The similar issue in Service Catalog: https://github.com/kubernetes-retired/service-catalog/issues/2276

**Comment by piotrmiskiewicz** [comment]
@kerenlahav - regarding the client creation. Is it the same in previous versions? Should we use 0.4.2 (or older)?

**Comment by kerenlahav** [comment]
Why do you have many reconciles? how many resources do you have? 
BTP operator use backoff mechanism in case of error, is there a general reconciliation issue?
please share more details on your scenario

client behavior is the same in all versions

**Comment by piotrmiskiewicz** [comment]
We observed OOM in a customer cluster. I don't know the details. The scenario I suspect is:
 - because of some errors, reconciliations are doing many times per second. I don't know where is the limit of GC. Let's imagine you are creating 50 service instances, polling interval is set to 10 seconds as I see. we have 5 calls per second. I know it is not a common situation. maybe there is another scenario I don't know now

**Comment by chuasweechin** [comment]
@piotrmiskiewicz In the environment that I observed the OOM issue, our cert-manager was running fine. I also observed  that there is 0 ServiceInstance and 0 ServiceBinding CR created in our cluster so I am not really sure if there are any reconciliation call in the environment.

I am currently upgrading btp-operator from v0.2.0 to v0.4.2. Once I am done with that, I will try to share more details.

**Comment by chuasweechin** [comment]
After upgrading the operator to v0.4.4, the issue seem to went away. Not sure why though.

**Comment by szwedm** [comment]
The issue still occurs, even on newer image versions.
<img width="1097" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/49093128/e67bcf39-9c42-4629-97ab-2f88b4d1fe42">
```
2023-10-03T09:27:57Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2023-10-03T09:27:57Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/mutate-services-cloud-sap-com-v1-serviceinstance"}
2023-10-03T09:27:57Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/mutate-services-cloud-sap-com-v1-servicebinding"}
2023-10-03T09:27:57Z	INFO	controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "services.cloud.sap.com/v1, Kind=ServiceBinding"}
2023-10-03T09:27:57Z	INFO	controller-runtime.builder	Registering a validating webhook	{"GVK": "services.cloud.sap.com/v1, Kind=ServiceBinding", "path": "/validate-services-cloud-sap-com-v1-servicebinding"}
2023-10-03T09:27:57Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/validate-services-cloud-sap-com-v1-servicebinding"}
2023-10-03T09:27:57Z	INFO	controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "services.cloud.sap.com/v1, Kind=ServiceInstance"}
2023-10-03T09:27:57Z	INFO	controller-runtime.builder	Registering a validating webhook	{"GVK": "services.cloud.sap.com/v1, Kind=ServiceInstance", "path": "/validate-services-cloud-sap-com-v1-serviceinstance"}
2023-10-03T09:27:57Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/validate-services-cloud-sap-com-v1-serviceinstance"}
2023-10-03T09:27:57Z	INFO	setup	starting manager
2023-10-03T09:27:57Z	INFO	controller-runtime.webhook.webhooks	Starting webhook server
2023-10-03T09:27:57Z	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
2023-10-03T09:27:57Z	INFO	starting server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
2023-10-03T09:27:57Z	INFO	controller-runtime.certwatcher	Updated current TLS certificate
2023-10-03T09:27:57Z	INFO	controller-runtime.webhook	Serving webhook server	{"host": "", "port": 9443}
2023-10-03T09:27:57Z	INFO	Starting EventSource	{"controller": "serviceinstance", "controllerGroup": "services.cloud.sap.com", "controllerKind": "ServiceInstance", "source": "kind source: *v1.ServiceInstance"}
2023-10-03T09:27:57Z	INFO	Starting EventSource	{"controller": "servicebinding", "controllerGroup": "services.cloud.sap.com", "controllerKind": "ServiceBinding", "source": "kind source: *v1.ServiceBinding"}
2023-10-03T09:27:57Z	INFO	controller-runtime.certwatcher	Starting certificate watcher
2023-10-03T09:27:57Z	INFO	Starting EventSource	{"controller": "servicebinding", "controllerGroup": "services.cloud.sap.com", "controllerKind": "ServiceBinding", "source": "kind source: *v1.Secret"}
2023-10-03T09:27:57Z	INFO	Starting Controller	{"controller": "servicebinding", "controllerGroup": "services.cloud.sap.com", "controllerKind": "ServiceBinding"}
2023-10-03T09:27:57Z	INFO	Starting Controller	{"controller": "serviceinstance", "controllerGroup": "services.cloud.sap.com", "controllerKind": "ServiceInstance"}
```
I think the container gets OOMKilled because of ServiceBinding controller's watcher for Secrets when there is a high number of Secrets in the cluster (500+).

**Comment by szwedm** [comment]
@kerenlahav 3 Service Instances and 3 Service Bindings. Please reopen the issue and look into controller watchers.

**Comment by kerenlahav** [comment]
the operator watches only secrets that are owned by bindings and not all cluster secrets
https://github.com/SAP/sap-btp-service-operator/blob/ad01aec1c2bb534fb6b49d46746a0c64dde7ffd7/controllers/servicebinding_controller.go#L455
I checked your theory and created 1000 secrets on my cluster, the operator started without any issues and reconciled all the resources successfully.
<img width="150" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/45451976/13ed26ca-24c0-413d-b121-31c625bdacd8">

we also use the BTP operator and never encountered this issue, if I can't reproduce it I have no way to investigate it, if you have any idea what should i check or how can i reproduce it i'll be happy to look into it

**Comment by szwedm** [comment]
@kerenlahav thanks for testing my theory, what was the memory consumption of the manager container when it was starting on the cluster with over 1000 Secrets?

**Comment by kerenlahav** [comment]
<img width="955" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/45451976/b8d62062-1deb-4191-8c0d-24f0830b54a4">
I have 1 service instance and 6 bindings

**Comment by szwedm** [comment]
the memory spike occurs during containers creation when Service Instance and Service Binding controllers start, check memory usage then.

**Comment by kerenlahav** [comment]
it was the first metric after startup..
I restarted again:
<img width="1699" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/45451976/9108ec24-016c-4865-8d5c-8c23e4fb62ad">

**Comment by szwedm** [comment]
@kerenlahav thanks for checking the memory usage. The issue is hard to reproduce. I created 2k Secrets with only one entry in data on a locally running cluster, deployed sap-btp-service-operator and saw an increase of the memory usage only by 35 MiB during controllers startup.
<img width="360" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/49093128/f9f07dc9-a6a6-4692-8069-6f512130b2f8">

Then I created 200 more Secrets with a lot of entires in data, restarted sap-btp-operator-controller-manager pod and it got OOMKilled. Here's the memory usage:
- before controllers startup

<img width="368" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/49093128/8330905e-249f-4632-9cf9-57d0b7a581e3">.

- during controllers startup

<img width="367" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/49093128/9dfa3a14-c8fe-48a7-a378-554edbe04b30">.

<img width="368" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/49093128/b8745700-7383-4524-9cc4-a7176ba254b8">.
  
<img width="368" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/49093128/c9301f84-f3d0-4937-9a92-a19c2f598643">.
  
- after container got OOMKilled
<img width="369" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/49093128/43b73ff2-709a-4283-9d43-18b5531dbba1">

**Comment by kerenlahav** [comment]
What is k3d-test-server?
I tried again, created 2000 more secrets (now i have more than 3000) with bigger data, but the memory is still not very high
<img width="1719" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/45451976/59b603a6-20c9-4b50-9b01-8de61a13002c">

**Comment by szwedm** [comment]
@kerenlahav `k3d-test-server-0` is my local k3d node. I got resources usage by calling `kubectl top node`. Two things to consider:
- OOMKilled occurs during controllers startup, before workers are started (see logs in one of the comments above),
- there should be a lot of Secrets in the cluster (800+ in case of the cluster where the issue occurred),
- Secrets should contain a lot of data (for tests I populated Secrets with over 3000 entries).
To address the issue, you can create a cache which will contain only selected Secrets (for example selected by labels) and pass it to the manager. See: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager@v0.16.2#Options.NewCache

**Comment by kerenlahav** [comment]
I don't understand how k3d is related to the BTP operator's code, what is it running? 
again, the BTP operator does not watch secrets, it watches serviceInstance and serviceBindings, why would secrets have an impact in the operator's startup?
I have more than 3000 secrets (6 entries, each value is 5000 chars) and during startup the memory is around 20-40m
